var AssetGraph = require('assetgraph');

var headers = [
    'Content-Security-Policy'
];

new AssetGraph({ root: 'dist' })
    .loadAssets('index.html')
    .populate({
        followRelations: { type: 'HtmlAnchor', crossorigin: false }
    })
    .queue(function (assetGraph) {
        var assets = assetGraph.findAssets({ type: 'Html', isInline: false });

        var headerMap = {};

        assets.forEach(function (asset) {
            var url = '/' + asset.url.replace(assetGraph.root, '').replace(/#.*/, '');

            headers.forEach(function (header) {
                var node = asset.parseTree.querySelector('meta[http-equiv=' + header + ']');

                if (node) {
                    if (!headerMap[url]) {
                        headerMap[url] = {};
                    }

                    headerMap[url][header] = node.getAttribute('content');

                    node.parentNode.removeChild(node);
                    asset.markDirty();
                }
            });
        });

        console.log('\n## Autogenerated headers:\n')

        Object.keys(headerMap).forEach(function (key) {
            console.log(key);

            var header = headerMap[key];

            Object.keys(header).forEach(function (headerKey) {
                console.log('  ' + headerKey + ': ' + header[headerKey]);
            });

            console.log('');
        });

    })
    .writeAssetsToDisc({ isLoaded: true })
    .run();
